/* Auto generated file by build envsetup shell.
 !!!!!!!! Do not edit this file. !!!!!!!!
 Created time : Fri May 30 13:32:42 KST 2014
TARGET_BUILD_BOARDVER : tp20
*/

#define CONFIG_BOARD_VER CONFIG_TP20

